=== sauravdhakal-11/web-technology-bca-lab/lab 2/Q13.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="hospital">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="patient" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="name">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="first" type="xs:string"/>
                    <xs:element name="middle" type="xs:string"/>
                    <xs:element name="last" type="xs:string"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="patient_number">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:pattern value="[0-9]{5}"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="doctor_name" type="xs:string"/>
              <xs:element name="diseases">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="disease" type="xs:string" maxOccurs="unbounded"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="charge">
                <xs:simpleType>
                  <xs:restriction base="xs:integer">
                    <xs:minInclusive value="500"/>
                    <xs:maxInclusive value="5000"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="lab_tests">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="test" type="xs:string" maxOccurs="unbounded"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== sauravdhakal-11/web-technology-bca-lab/lab 2/Q13.xml
<?xml version="1.0" encoding="UTF-8"?>
<hospital xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Q13.xsd">
    <patient>
        <name>
            <first>John</first>
            <middle>Quincy</middle>
            <last>Doe</last>
        </name>
        <patient_number>12345</patient_number>
        <doctor_name>Dr. Smith</doctor_name>
        <diseases>
            <disease>Hypertension</disease>
            <disease>Diabetes</disease>
        </diseases>
        <charge>1500</charge>
        <lab_tests>
            <test>Blood Count</test>
            <test>Glucose Level</test>
        </lab_tests>
    </patient>
</hospital>
